### ISSUE TITLE
nfc乘车方式可以新增2种

### ISSUE THREAD

**Issue by Mongoose110** [Ivysauro/CNRT#13]
可以新增2个nfc公交卡的信息。
国内：
微信小程序“轻松乘车”，是一个基于ese模式开卡的微信小程序。只支持华为。
目前支持的城市有：广西桂民卡、海南一卡通、烟台市民卡。

国外：
迪拜公交卡
https://mp.weixin.qq.com/s/HmZLv6QeAFPg5YA5lH-yqA
---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
迪拜公交卡我看到消息了，不过本项目目前暂时只统计国内公交卡的支持情况（毕竟叫China Rail Transit🤣）

小程序“轻松乘车”考虑收录，但还没有想好怎么呈现😅

**Comment by Ivysauro** [comment]
感觉这个”轻松乘车“实质上是不是在华为钱包里开了一张卡🤔

**Comment by Mongoose110** [comment]
> 感觉这个“轻松乘车”投放是不是在华为钱包里开了一张卡🤔

没错，直接往se里面下apud指令。

微信可以访问se，华为为微信开放了能力。

**Comment by Ivysauro** [comment]
> > 感觉这个“轻松乘车”投放是不是在华为钱包里开了一张卡🤔
> 
> 没错，直接往se里面下apud指令。
> 
> 微信可以访问se，华为为微信开放了能力。

那这个只能算到华为里面了……

**Comment by Mongoose110** [comment]
> > > 感觉这个“轻松乘车”投放是不是在华为钱包里开了一张卡🤔
> > 
> > 
> > 没错，直接往se里面下apud指令。
> > 微信可以访问se，华为为微信开放了能力。
> 
> 那这个只能算到华为里面了……

未来应该会逐步开放能力给微信，短期看来各家oem对微信这些的第三方应用接入都挺保守的。
