### ISSUE TITLE
建议「轨道交通支付方式」将桃园捷运、新北轻轨单独列出

### ISSUE THREAD

**Issue by hoginwang** [Ivysauro/CNRT#17]
桃园机场捷运、新北轻轨都是独立营运，建议「轨道交通支付方式」将桃园捷运、新北轻轨单独列出。以及桃园机场捷运支持银联信用卡闪付。

**Comment by Ivysauro** [comment]
可以考虑，毕竟从行政区划上都算三个城市😂
但分开后新北只有有轨电车，就暂不收录了（有空会把有轨电车的数据收录，单独列出

**Comment by Ivysauro** [comment]
已拆分。
桃园机场捷运支持银联信用卡闪付有来源吗？我没有找到相关报道。

**Comment by hoginwang** [comment]
> 已拆分。
> 
> 桃园机场捷运支持银联信用卡闪付有来源吗？我没有找到相关报道。

[行動支付信用卡 - 桃園捷運](https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/ticketson05.php)

另外建议轨道交通、地面公交都加一栏是写Visa、Mastercard、JCB的。

**Comment by hoginwang** [comment]
@Ivysauro 
另外关于港铁支持二维码过闸：
1. 根据多家内地媒体报道，港铁二维码过闸也将支持内地支付宝。[明年一月起香港地铁可用支付宝扫码过闸 - 界面新闻](https://m.jiemian.com/article/5448821.html) [30天后，港铁用AlipayHK和支付宝均可扫码进闸 - 深圳新闻网](http://www.sznews.com/news/content/mb/2020-12/25/content_23838802.htm)
  Alipay HK及港铁新闻稿没有提及内地支付宝。
  目前支付宝有款港铁的小程序提示仍在测试中，另有一款港铁补回入闸记录的小程序已可以打开。
2. 二维码过闸只支持除机场快线以外的重铁路线，轻铁及港铁巴士都不支持，需要注明。

**Comment by Ivysauro** [comment]
> > 已拆分。
> > 桃园机场捷运支持银联信用卡闪付有来源吗？我没有找到相关报道。
> 
> [行動支付信用卡 - 桃園捷運](https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/ticketson05.php)
> 
> 另外建议轨道交通、地面公交都加一列是写Visa、Mastercard、JCB的。

桃园数据已更新。

感觉加一列外卡组织没必要吧，毕竟目前内地/大陆城市没一个支持的。

**Comment by hoginwang** [comment]
> > > 已拆分。
> > > 桃园机场捷运支持银联信用卡闪付有来源吗？我没有找到相关报道。
> > 
> > 
> > [行動支付信用卡 - 桃園捷運](https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/ticketson05.php)
> > 另外建议轨道交通、地面公交都加一列是写Visa、Mastercard、JCB的。
> 
> 桃园数据已更新。
> 
> 感觉加一列外卡组织没必要吧，毕竟目前内地/大陆城市没一个支持的。

体现港澳台属于中国呀。而且做成双语不是为了给外语使用者看？既然是方便外语使用者的资料，顺便写上了挺合理的。

**Comment by Ivysauro** [comment]
> > > > 已拆分。
> > > > 桃园机场捷运支持银联信用卡闪付有来源吗？我没有找到相关报道。
> > > 
> > > 
> > > [行動支付信用卡 - 桃園捷運](https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/ticketson05.php)
> > > 另外建议轨道交通、地面公交都加一列是写Visa、Mastercard、JCB的。
> > 
> > 
> > 桃园数据已更新。
> > 感觉加一列外卡组织没必要吧，毕竟目前内地/大陆城市没一个支持的。
> 
> 体现港澳台属于中国呀。而且做成双语不是为了给外语使用者看？既然是方便外语使用者的资料，顺便写上了挺合理的。
> 
> 可以采取内地部分没有外卡这一列的方法显示。

方便外语使用者和专门加一栏外卡组织没有必然联系吧🤔

内地部分不显示外卡……地面交通这边可以，轨道交通这边不太好弄

**Comment by Ivysauro** [comment]
国际卡加上了😏 用来~~作法~~期待更多城市支持吧

**Comment by emoust** [comment]
这么说的话高雄也是支持VIsa/JCB 的Contactless的
ref: https://www.krtc.com.tw/Ticket/ticket_more?id=9f77e20ca65049bd9ee65ece382844af

**Comment by Ivysauro** [comment]
> 这么说的话高雄也是支持VIsa/JCB 的Contactless的
> ref: https://www.krtc.com.tw/Ticket/ticket_more?id=9f77e20ca65049bd9ee65ece382844af

是的，已更新。感谢反馈。

**Comment by chenw23** [comment]
> 国际卡加上了😏 用来~作法~期待更多城市支持吧

3年后回顾：北京是内地首个全面支持的城市，在2024年Q3已全面支持 Visa/Mastercard外卡刷卡过闸机。🥳
