### ISSUE TITLE
“之最”中 最长的全地下线路 应更新为 成都地铁6号线

### ISSUE THREAD

**Issue by hbmaak** [Ivysauro/CNRT#18]
https://zh.wikipedia.org/wiki/%E6%88%90%E9%83%BD%E5%9C%B0%E9%93%816%E5%8F%B7%E7%BA%BF

https://zh.wikipedia.org/wiki/%E5%B9%BF%E5%B7%9E%E5%9C%B0%E9%93%813%E5%8F%B7%E7%BA%BF
---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
已更新，谢谢反馈~
