### ISSUE TITLE
郑州地铁支持银联云闪付扫描二维码购票

### ISSUE THREAD

**Issue by maimendong** [Ivysauro/CNRT#21]
![1620722741788](https://user-images.githubusercontent.com/34152532/117787469-0b947e00-b279-11eb-890b-7ba962e56732.jpg)

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
已更新，谢谢反馈。

大佬可以考虑下直接提交PR😂
