### ISSUE TITLE
北京14号线中段 暂缓开通的界定问题

### ISSUE THREAD

**Issue by SierraQin** [Ivysauro/CNRT#30]
data/SpSta.md  Line 90 
```
- ~~西铁营、菜户营、东管头~~（14号线，2015.12-2021.12）
```
14号线中段四站在当时完全没有修建，因此我认为其不符合暂缓或预留的标准，应考虑从暂缓列表中移除。

**以及刚刚手滑把平安里粘贴成新街口了**，如上述建议被采纳，我晚些一并PR。

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
同意从暂缓列表中移除。
