### ISSUE TITLE
辽宁健康码建议添加盛事通

### ISSUE THREAD

**Issue by ghhcbef1** [Ivysauro/CNRT#47]
如题

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
感谢反馈

**Comment by Ivysauro** [comment]
不过搜了一下，这个盛世通这么不受待见吗😂

https://zhuanlan.zhihu.com/p/563197857

**Comment by Ivysauro** [comment]
已更新
