### ISSUE TITLE
NFC交通卡信息更新

### ISSUE THREAD

**Issue by redaiert2** [Ivysauro/CNRT#53]
1、微信乘车卡小程序已经通告8月7日停止运营。新的交通乘车卡小程序中没有红山通，但新增了羊城通，其他暂无变更。

2、中兴卡包里现有29张卡，不知是否有兴趣添加一下？~~比珠海小厂还多不是？~~
      现有：武汉通、燕赵通、大连明珠卡、吉林通、哈尔滨城市通、琴岛通、潇湘卡、天津城市一卡通、长安通、绿城通、江苏城市一 
      卡通 苏州·南通、绍兴交通一卡通、厦门一卡通、合肥通、广西桂民卡、京津冀互联互通卡、岭南通系列卡（羊城通、广佛通、红 
      海通、五邑通、肇庆通、韶州通、河源粤支付、漠江通、茂城通、榕江通、岭云通、潮州通）。
      
以上除了武汉通以外均为交联卡。

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
👍
1.微信乘车卡的变更会核实更新
2.中兴（努比亚）交通卡数据官网未公布，网上也没有相关信息，感谢提供数据

**Comment by redaiert2** [comment]
> 👍 1.微信乘车卡的变更会修复更新 2.中兴（努比亚）交通卡数据官网未公布，网上也没有相关信息，感谢提供数据

1、有劳了。

2、中兴对于NFC方面似乎不是很上心。论坛和官网也确实找不到这类信息。但正好手里有努比亚的设备，后续有什么变动的话，我这边看到了会再提交issues。

**Comment by Ivysauro** [comment]
#54 已更新，欢迎继续反馈
