### ISSUE TITLE
小米NFC交通卡信息更新

### ISSUE THREAD

**Issue by redaiert2** [Ivysauro/CNRT#57]
小米新上线金华市民卡·八婺通交联版。

看表格数据，这似乎也是八婺通第一个NFC交联版？

![Picture_1690837574340](https://github.com/Ivysauro/CNRT/assets/26710960/ce0b96d4-b715-4e04-884e-7562bd471c61)

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
谢谢提供线索
#58 已更新
