### ISSUE TITLE
【赣州市】地面公交支付方式补充

### ISSUE THREAD

**Issue by pickmefly** [Ivysauro/CNRT#62]
* 汇通行APP已于2020年12月1日下线，终止与赣州公交合作。
source: https://mp.weixin.qq.com/s/c-wFWTmh3MlABYC1ZHHC8A

* 微信没有直接支持乘车码，不过可以通过“赣州通”公众号或者“市民出行”小程序打开“赣州乘车码”，可以选择充值到小程序钱包或者开通免密支付。
![image](https://github.com/Ivysauro/CNRT/assets/36589961/91592a0d-7c32-421f-9406-7d75635c150b)
![image](https://github.com/Ivysauro/CNRT/assets/36589961/6df25130-e439-4077-9564-3c305dbc01df)

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
已更新，谢谢反馈
