### ISSUE TITLE
宁波轨道交通4号线开通 同名站奥体中心应计入

### ISSUE THREAD

**Issue by EthanJenny** [Ivysauro/CNRT#7]
---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
感谢您的提醒，今年下半年开通的线路的信息将在年底统一更新（最近太忙了😂

**Comment by Ivysauro** [comment]
已更新
https://github.com/Ivysauro/CNRT/blob/master/data/Namesake.md
