### ISSUE TITLE
关于天津西站安检互认的现状

### ISSUE THREAD

**Issue by ShuJun-Junical** [Ivysauro/CNRT#83]
天津西站火车站和西站地铁站的安检互认现在是单向的，从火车站进入地铁站无需安检，但从地铁站进入火车站候车厅需要再次安检。

数据来源是本人实地乘坐得知。本人于 23 年 12 月、24 年 1 月多次在天津西站换乘地铁。

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
是的 很多数据都是来源于当时开通时的新闻通稿 感谢提供目前的实际状态

**Comment by Ivysauro** [comment]
很遗憾该车站安检互认被降级

**Comment by Ivysauro** [comment]
数据已更新
#92
