### ISSUE TITLE
南京地铁部分数据更新

### ISSUE THREAD

**Issue by galaxyhere** [Ivysauro/CNRT#85]
[南京地铁7号线目前为南北分段运营](https://new.qq.com/rain/a/20231228A06JF200)
[南京地铁5号线竹山路站目前与1号线竹山路站出站虚拟换乘](https://www.sohu.com/a/768176294_121321033)
---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
#86 分段运营已更新

**Comment by Ivysauro** [comment]
完成✅
