### ISSUE TITLE
撤下健康码相关内容

### ISSUE THREAD

**Issue by AndrewFengNJXL** [Ivysauro/CNRT#88]
鉴于现实情况，健康码可以撤下来了，或者是标记成灰色，提醒人们勿忘耻辱（bushi，保留历史记忆

---
如您要指出数据库中的错误，最好给出消息来源/ If you want to point out errors in the database, it is best to give the source

**Comment by Ivysauro** [comment]
有道理

**Comment by Ivysauro** [comment]
完成✅
